# See the documentation for more information:
# https://packit.dev/docs/configuration/

upstream_project_url: https://github.com/systemd/mkosi
jobs:
  - job: pull_from_upstream
    trigger: release
    dist_git_branches:
      - fedora-rawhide
  - job: koji_build
    trigger: commit
    dist_git_branches:
      - fedora-rawhide
  - job: bodhi_update
    trigger: commit
    dist_git_branches:
      - fedora-rawhide
